### ISSUE TITLE
Rename interfaces to ..Interface

### ISSUE THREAD

**Issue by Revisor** [mcordingley/Regression#1]
What do you think about following the internal PHP-FIG conventions and naming all interfaces ..Interface?
I would also move the interfaces one level deeper, `LinkingInterface` into `mcordingley\Regression\Linking` and `RegressionStrategyInterface` into `mcordingley\Regression\RegressionStrategy`

See https://github.com/php-fig/fig-standards/blob/master/bylaws/002-psr-naming-conventions.md

It would make the code just a little bit more readable.

**Comment by mcordingley** [comment]
I'm all for following standards and a community-level style-guide, even if that means having to adapt my own personal style. However, the PHP-FIG conventions on this feel redundant. I'm not sure how I feel about that, yet.

**Comment by Revisor** [comment]
No problem, just a suggestion.

Should you decide to do it, it's easier to do it now, before it's stable.

**Comment by mcordingley** [comment]
Nope, it feels cleaner to do it this way. I also renamed the RegressionStrategy to something more descriptive while I was at it.

**Comment by Revisor** [comment]
Thumbs up, the renaming made it clearer.

**Comment by mcordingley** [comment]
Iterate to perfection. :)

On Tue, Mar 3, 2015 at 11:16 AM, Revisor notifications@github.com wrote:

> Thumbs up, the renaming made it clearer.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mcordingley/Regression/issues/1#issuecomment-76976786
> .

## 

Michael Cordingley
740.707.7809
