### ISSUE TITLE
How would you calculate the significance of the correlation (relationship)?

### ISSUE THREAD

**Issue by Revisor** [mcordingley/Regression#3]
I'm a self-taught beginner in statistics and I'm still wrapping my head around the concepts as I go, so please feel free to correct anything I say.

With that said, I would like to be able to perform a linear regression on some data and than calculate the statistical significance of the regression based on the correlation coefficient and the number of data points. 

Basically I want to know 
- the direction of the trend (the slope of the line from linear regression)
- the strength of the relationship (the coefficient of determination, aka R-Squared)
- and the significance of the relationship, calculated with a pretty complicated formula, or read from a table:

See http://www.oneonta.edu/faculty/vomsaaw/w/psy220/files/SignifOfCorrelations.htm

How would you suggest I go about getting the significance of the correlation?

Is it something that makes sense to include in this library? Should I include it in a wrapper, a level above?

(For my own future reference
http://vassarstats.net/rsig.html - calculates significance from r and N, but the code in JS is ugly
http://janda.org/c10/Lectures/topic06/L24-significanceR.htm - more notes about strength and significance)

**Comment by Revisor** [comment]
Or in other words: Can I use the square root of R-Squared to calculate the significance of the correlation? I lose the sign but it shouldn't matter, right.

What do you think about making the correlation accessible as well, if the library is already calculating R-Squared?

**Comment by mcordingley** [comment]
If you're looking to see if the regression itself is significant, calculate the F statistic for it and compare that against a table of F values or the F distribution. Don't try to figure out if the r-squared is significant. That's not going to be a very meaningful line of questioning. Go with the F route.

The library does not yet have a way to calculate the F statistic for you, though I do plan on including that later on. The F distribution is out of scope for this library, but would appear in another one, if I could just get some of the prerequisites out of the way.

Hopefully none of this seems terse; it's late and I'm done for.

**Comment by Revisor** [comment]
Thank you, I'll have a look at the F statistic.
